### ISSUE TITLE
 Deploy Contínuo

### ISSUE THREAD

**Issue by alvesisaque** [Dulce-Work-Schedule/2018.1-Dulce_App#216]

**Comment by alvesisaque** [comment]
Essa issue é um débito técnico, mas não foi priorizada para a próxima sprint devido a prioridade e o risco do grupo estar codando a API sem uma integração contínua.

**Comment by eliseuegewarth** [comment]
links úteis para deploy continuo do aplicativo com a ferramenta fastlane:
https://fastlane.tools/
https://docs.fastlane.tools/getting-started/android/beta-deployment/
https://docs.fastlane.tools/getting-started/android/setup/#setting-up-supply

**Comment by egewarth** [comment]
@eliseuegewarth 👏👏

**Comment by gag2502** [comment]
@eliseuegewarth Eu dei uma olhada e parece ser maravilhosa ! ❤️

**Comment by egewarth** [comment]
issue reaberta por instabilidade na solução.
