### ISSUE TITLE
Tratamento de exceção de conexão

### ISSUE THREAD

**Issue by vitorl-s** [Dulce-Work-Schedule/2018.1-Dulce_App#239]
Nessa issue deve ser feito:
- Tratamento de exceção quando a API não consegue se comunicar com a rede

**Comment by egewarth** [comment]
@vitorl-s , as labels estão todas erradas kkkk, semana que vem haverá treinamento para criação de issues melhores, vocês vão passar a criar mais issues e participar mais ativamente delas.

**Comment by vitorl-s** [comment]
@egewarth kkkkkkkk desculpa, vou corrigir depois
