### ISSUE TITLE
Observar e identificar as dificuldades das atividades do UX

### ISSUE THREAD

**Issue by BeatrizHanae** [Dulce-Work-Schedule/2018.1-Dulce_App#263]
Observar os usuários finais e identificar os problemas e dificuldades que existem no ambiente de trabalho.

Nessa issue será realizado:
- Obervação;
- Anotação dos problemas;
- Sugestões possíveis de soluções.
- Navegabilidade estrutural

**Comment by egewarth** [comment]
como essa issue foi priorizada essa semana sendo que ela tem uma dependencia de uma issue que não foi priorizada? Essa dependencia existe?

**Comment by alvesisaque** [comment]
@fepas @gdeusdara essa issue também vai ser débito técnico?

**Comment by BeatrizHanae** [comment]
Pensando mais sobre e Navegabilidade estrutural, inclusive importante para o protótipo:
     Diagrama de navegação.
         Sitemap/AppMap:
         Organizar a hierarquia do site/app 
         Organizar de um jeito que o usuário encontre as informações
     Entender o que precisa ser criado ou  que esta faltando.
     Wireframes (ótimo para prototipação);

**Comment by BeatrizHanae** [comment]
@egewarth O Profissional da saúde, poderá ver a escala do setor mesmo?
Por exemplo: João vê se Maria está trabalhando naquele mesmo horário que ele.

**Comment by egewarth** [comment]
@BeatrizHanae Claro, se não não haveria sentido em ter troca de escalas sem poder ver a escala do outro

**Comment by BeatrizHanae** [comment]
@egewarth ok.

**Comment by BeatrizHanae** [comment]
@egewarth Você pediu para os meninos responsáveis pelo protótipo, da issue 272 , de colocar um botão/navegação para solicitar férias... Atualmente como isso é feito? Eles preenchem papel? Manda um zap para o gestor combinando? Burocracias? Não? Sim?

**Comment by egewarth** [comment]
@BeatrizHanae deus, quanta pergunta dificil. Eles mandam zap, sinal de fumaça, email, qq coisa.
