### ISSUE TITLE
Criar protótipo baseado no profissional da saúde.

### ISSUE THREAD

**Issue by BeatrizHanae** [Dulce-Work-Schedule/2018.1-Dulce_App#272]
Essa issue é para criação de um protótipo que abrange a parte do escopo de visualização de escalas do profissional da saúde, logo deverá ser feito:

- Tela para login
- Tela para edição de perfil 
  - Botão para deletar
  - Dados do usuário
- Tela para visualização do perfil
  - Dados do usuário
  - Botão para edição
- Tela para Visualização de escala do setor
- Tela para visualização de escala do médico
- Local na escala para solicitar troca de plantão
- Local para solicitar periodo de férias (sidebar)
- Local para solicitar abono de falta por atestado médico (sidebar)

**1ø Code Review**  02/05 ás 21h
**2ø Code Review**  04/05 ás 23h

**Comment by gdeusdara** [comment]
@egewarth eu estava olhando o invisionapp hj, achei muito bom, até por ser de graça, mas precisa de windows

**Comment by egewarth** [comment]
@gdeusdara nenhum da dupla tem? talvez um dual boot

**Comment by gdeusdara** [comment]
@egewarth acho que o jimmy tem, ta tranquilo

**Comment by egewarth** [comment]
@gdeusdara Deusdará e Jimmy, quero que mantenham contato cmg pra qualquer dúvida (chama no probleminha)

**Comment by egewarth** [comment]
@gdeusdara Deusdará e Jimmy, quero que mantenham contato cmg pra qualquer dúvida [chama no probleminha](https://github.com/fga-gpp-mds/2018.1-Dulce_App/issues/272#issuecomment-385508287)

**Comment by vitorl-s** [comment]
@egewarth Chamarei kkkkk

**Comment by gag2502** [comment]
@egewarth Chama no probleminha é ótimo 😂😂😂

**Comment by egewarth** [comment]
@gag2502 Issue = probleminha

**Comment by gag2502** [comment]
@egewarth Aaaaahhhhh 😂😂😂😂

**Comment by egewarth** [comment]
Galera, vi que estão com duvidas sobre qual ferramenta usar, sugiro que usem o proto.io em conjunto com o mockup.io. O Proto.io free tem muitas features relacionadas a IOS e Android, porém não da pra fazer a ligação entre as telas, que é justamente oq o mockup.io faz. No mockup.io você cria campos clicavéis que podem ter um comportamento, dai é só dar upload em algum print do proto.io e fazer as ligações, ou até mesmo fazer as ligações ao estilo storyboard do IOS.
<img width="295" alt="storyboard-example" src="https://user-images.githubusercontent.com/12779174/39501982-41a5ab24-4d94-11e8-9d6c-ebbbb817681d.png">

**Comment by egewarth** [comment]
Antes de tentarem do jeito que eu falei, procurem soluções melhores, a minha é uma gambiarra

**Comment by vitorl-s** [comment]
@egewarth Na tela inicial é pra colocar um botão de cadastro? Já que para o app não seria bom qualquer pessoa poder se cadastrar

**Comment by egewarth** [comment]
@vitorl-s Pode colocar

**Comment by alvesisaque** [comment]
@egewarth Gente, isso não faz sentido algum. O aplicativo só será utilizado por plantonistas de instituições que contrataram a Dulce. Vale a pena colocar uma observação no fim da página informando se a sua instituição ainda não tem a Dulce entrar em contato com o nosso e-mail

**Comment by fepas** [comment]
É realmente necessário o botão para deletar?

**Comment by fepas** [comment]
@egewarth

**Comment by egewarth** [comment]
@fepas Fale

**Comment by egewarth** [comment]
@fepas Deletar onde? Usuário?

**Comment by fepas** [comment]
Sim, como diz a issue

**Comment by egewarth** [comment]
pode manter

**Comment by egewarth** [comment]
@fepas

**Comment by fepas** [comment]
Quais são os dados pra serem editados na tela de edição @egewarth?

**Comment by egewarth** [comment]
@fepas Vocês não fizeram uma tela de cadastro não é? Se fizeram utilizem os mesmos dados

**Comment by fepas** [comment]
Não fizemos

**Comment by egewarth** [comment]
@fepas Puts, não estou me recordando os dados do usuário no momento, se você conseguir ver acredito que tenha na issue de edição do usuário

**Comment by gdeusdara** [comment]
Estamos fazendo uma tela inicial, de boas?

**Comment by egewarth** [comment]
@gdeusdara tela inicial vc fala uma home?

**Comment by gdeusdara** [comment]
@egewarth https://invis.io/69IDRDLG3CM#/296253671_Login

**Comment by gdeusdara** [comment]
@egewarth sim, se liga no link que eu mandei, é o prototipo funcionando

**Comment by egewarth** [comment]
@gdeusdara Continuem assim, acho que falta umas coisinhas ainda

**Comment by gdeusdara** [comment]
@egewarth Falta o que? Kkkk

**Comment by gdeusdara** [comment]
@egewarth https://invis.io/ZUIGR5S9CHQ#/296253671_Login    Novo link do protótipo ai, da uma olhada
