### ISSUE TITLE
Treinamento de Scrum e XP

### ISSUE THREAD

**Issue by egewarth** [Dulce-Work-Schedule/2018.1-Dulce_App#286]
Nessa issue deve ser feito:
- Principios de Scrum
- Principios do XP

**Comment by RochaCarla** [comment]
Aproveita e fala do lean/lean startup..
estou testando (e tendo excelentes resultados) em design sprint (tem umas técnicas interessantes que valem a pena serem testadas):

https://brasil.uxdesign.cc/google-design-sprint-como-funciona-e-como-aplicar-no-seu-projeto-279107363659

https://designsprintkit.withgoogle.com/

**Comment by egewarth** [comment]
@RochaCarla Vlw @RochaCarla, vamos pesquisar sobre
