### ISSUE TITLE
Remodelar documento de arquitetura

### ISSUE THREAD

**Issue by egewarth** [Dulce-Work-Schedule/2018.1-Dulce_App#290]
Nessa issue deve ser feito:
- Refazer diagrama de classes
  - Corrigir "atores" do sistema
  - Corrigir escalas - horários
  - Corrigir hospital - setor
  - Revisar todas as outras classes

- Metas e restrições de arquitetura
  - Microserviços
  - Secretaria de saúde

**Comment by eliseuegewarth** [comment]
@gdeusdara @fepas Tem que remodelar o usuário também.
Adequar a realidade de que um plantonista pode ter matrícula em mais de um setor/instituição.

**Comment by eliseuegewarth** [comment]
Sugestão:
- Informações do Usuário:
    - Nome/Sobrenome (preferivel que sejam 2 campos/atributos diferentes)
    - email
    - senha
- Informações sobre Contas (o cadastro que o plantonista tem em cada instituição):
    - Matrícula do plantonista
    - Identificador da Instituição
    - Identificador do Usuário

**Comment by gdeusdara** [comment]
@eliseuegewarth Beleza

**Comment by gdeusdara** [comment]
Na nova modelagem terá os atores supervisor geral e gerente de pessoas?

**Comment by egewarth** [comment]
@gdeusdara Não

**Comment by egewarth** [comment]
@gdeusdara Serão 3 atores apenas, um gestor, um plantonista e um supervisor geral. Mas ator não implica em classe, fiquem espertos

**Comment by gdeusdara** [comment]
@egewarth outra coisa, esse Contas descrito pelo @eliseuegewarth é uma classe que vai estar entre a classe Usuario e a Hospital interligando elas?

**Comment by egewarth** [comment]
@gdeusdara O usuário que a gente conhece hj vai virar esse "contas" (a gente não achou um nome melhor).
O usuário vai fazer login via Google (login social) e lá dentro ele vai poder cadastrar perfils pra diferentes locais de trabalho.

**Comment by egewarth** [comment]
@gdeusdara um nome melhor pode ser perfil

**Comment by egewarth** [comment]
@gdeusdara profiles no caso

**Comment by vitorl-s** [comment]
@egewarth @eliseuegewarth nessa nova refatoração do documento, só é necessário alterar o diagrama de classes?
