### ISSUE TITLE
Planejar Release

### ISSUE THREAD

**Issue by egewarth** [Dulce-Work-Schedule/2018.1-Dulce_App#292]
Nessa issue deve ser feito:
- Planejamento da Release (Sprints 8-15)
- Roadmap

Horários: Terça e/ou Quinta 8:30-10h

**Comment by alvesisaque** [comment]
Essa issue será priorizada para essa semana?

**Comment by egewarth** [comment]
Foi priorizada e comentada em reunião, inclusive com os horários marcados, porém não estava documentada.

**Comment by alvesisaque** [comment]
@egewarth @eliseuegewarth @gag2502 podemos fazer isso na nossa reunião de amanha às 8?

**Comment by egewarth** [comment]
@alvesisaque Era esse o horário planejado inicialmente

**Comment by alvesisaque** [comment]
@egewarth Que ágil. Confirmado, então 👍🏽

**Comment by egewarth** [comment]
@alvesisaque Espero não termos o fator impedimento Felipe César kkk

**Comment by egewarth** [comment]
@alvesisaque @eliseuegewarth @gag2502 , qual a pontuação?

**Comment by eliseuegewarth** [comment]
O Roadmap foi atualizado até a sprint 12.
As próximas sprints não foram modificadas por conta de incertezas.

**Comment by egewarth** [comment]
@alvesisaque @eliseuegewarth @gag2502 , acabei esquecendo de uma issue importante, que seria priorizada pra essa semana e acabou sendo postergada. A issue de visualização de escala por setor.
