### ISSUE TITLE
Prototipo

### ISSUE THREAD

**Issue by egewarth** [Dulce-Work-Schedule/2018.1-Dulce_App#297]
Nessa issue deve ser feito:
- Evolução do prototipo para possibilitar pesquisas com usuários
- Tela inicial deve ser escala por semana (Feedback do Getulio)
- Tela de escala por semana
- Funcionalidade completa de troca de escalas
- Aplicação do Sitemap (Navegabilidade)

**Comment by BeatrizHanae** [comment]
@egewarth prototipo de alta fidelidade ou media ainda?

**Comment by egewarth** [comment]
@BeatrizHanae Eu estou em dúvida sobre, mas acredito que seja média

**Comment by BeatrizHanae** [comment]
@egewarth Então, o de média, pelo q eu vi de exemplos em outros projetos (seja de mds/eps ou outros lugares), eles não têm desing ainda, cores e tals. O de alta sim, por mais q esteja um de alta bem superficial, eu acho q é mais de alta do q média por ter interação entre telas já e tals :)
