### ISSUE TITLE
Visualizar escala - mês/dia/horário - visual

### ISSUE THREAD

**Issue by gabibguedes** [Dulce-Work-Schedule/2018.1-Dulce_App#298]
Nessa issue será realizado:
- Criação da tela de visualizar horários no mês de um setor

Critérios de aceitação:
- Os dados devem ser apenas de exemplo, sem conexão com a API
- A tela deve ter o calendário e a visualização dos horários do dia]
- Deve seguir minimamente o prototipo desenhado (podendo ter alterações validadas pelo PO)

**Comment by BeatrizHanae** [comment]
@gdeusdara será que você pode me ajudar em relação a tamanho da fonte e o sidebar?
