### ISSUE TITLE
Visualizar escala - mês/dia/horário - validação

### ISSUE THREAD

**Issue by fepas** [Dulce-Work-Schedule/2018.1-Dulce_App#301]
Nessa issue será realizado:

Validações da tela de visualizar horários no mês de um setor em relação á conexão com a API

Critérios de aceitação:
- [ ] Validação de conexão com a internet;
- [ ] Validação da existencia de dados;
- [ ] Validação de lista vazia;

**Comment by vitorl-s** [comment]
A issue foi fechada e pontuação foi alterada para 0, porque a issue #308 resolve o mesmo problema.
