### ISSUE TITLE
Visualizar escala - semana/dia/horário - funcionalidade

### ISSUE THREAD

**Issue by BeatrizHanae** [Dulce-Work-Schedule/2018.1-Dulce_App#303]
Nessa issue deve ser feito:
- Funcionalidade da tela de visualização de escala por semana.
- Requisições Axios
- Redux
- Modificar o que foi feito no visual para imprimir dados na tela

**Comment by gabibguedes** [comment]
Pra que precisamos do redux nessa issue?
