### ISSUE TITLE
Monitoramento e Controle da Arquitetura

### ISSUE THREAD

**Issue by alvesisaque** [Dulce-Work-Schedule/2018.1-Dulce_App#305]

**Comment by egewarth** [comment]
Oq será feito nessa issue?

**Comment by egewarth** [comment]
Ela é aplicada a essa sprint mesmo sem a equipe trabalhar na API?

**Comment by alvesisaque** [comment]
Sim, essa issue visa monitorar e controlar a evolução de toda a arquitetura, não somente dos microsserviços. É incluso as verificações e validações de documentos e a arquitetura do aplicativo.
