### ISSUE TITLE
Visualizar escala - mês/dia/horário - Funcionalidade

### ISSUE THREAD

**Issue by gdeusdara** [Dulce-Work-Schedule/2018.1-Dulce_App#306]
Nessa issue será realizado:
- [ ] Integração do Front End com a API

Critérios de aceitação:
- Requisição Axios
- Salvar em um objeto (Redux)
- modificar o que foi feito no visual para imprimir dados na tela

**Comment by vitorl-s** [comment]
A issue foi fechada e pontuação foi alterada para 0, porque a issue #303  resolve o mesmo problema
