### ISSUE TITLE
Elaborar Backlog do produto

### ISSUE THREAD

**Issue by egewarth** [Dulce-Work-Schedule/2018.1-Dulce_App#309]
Nessa issue será realizado:
- Criação das issues das funcionalidades planejadas release 2 (até a sprint 15)

**Comment by eliseuegewarth** [comment]
# Nessa issue foi criado o backlog do produto:
## Report:
 - #[1](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_Report/issues/1)
 - #[2](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_Report/issues/2)
 - #[3](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_Report/issues/3)
 - #[4](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_Report/issues/4)
 - #[5](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_Report/issues/5)
 - #[6](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_Report/issues/6)

## User:
 - #[12](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_User/issues/12)
 - #[13](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_User/issues/13)

## App:
 - #[315](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_App/issues/315)
 - #[317](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_App/issues/317)
 - #[319](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_App/issues/319)
 - #[320](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_App/issues/320)

## Schedule:
 - #[1](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_Schedule/issues/1)
 - #[11](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_Schedule/issues/11)
 - #[12](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_Schedule/issues/12)
 - #[13](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_Schedule/issues/13)
 - #[14](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_Schedule/issues/14)
 - #[15](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_Schedule/issues/15)

## Login:
 - #[10](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_Login/issues/10)
