### ISSUE TITLE
Trocar de plantão

### ISSUE THREAD

**Issue by egewarth** [Dulce-Work-Schedule/2018.1-Dulce_App#315]
Eu, como plantonista, gostaria de trocar de plantão com outro plantonista a fim de adequar meus horários.

Critérios de aceitação:
- Troca de horários ser efetivada para ambos os médicos
- [Solicitante] Ao ver escala do setor permitir clicar no horário de outro plantonista e solicitar a troca
- [Solicitado] Visualizar de pedidos de troca de plantão

Validações:
- Não exceder horas maximas por dia
- Não exceder horas maximas por semana
- Não exceder horas maximas por mês
- Não permitir diminuir as horas minimas por semana
- Não permitir diminuir as horas minimas por mês

Observações:
- [Solicitado] Receber notificação sobre pedido de troca de plantão
- [Ambos] Receber notificação sobre confirmação de troca de escalas

**Comment by alvesisaque** [comment]
@egewarth @eliseuegewarth @EzequielDeOliveira @gdeusdara @gag2502 

Esse épico não possui nenhuma issue ligada a ele.
