### ISSUE TITLE
Revisar uso do burndown de riscos 

### ISSUE THREAD

**Issue by gag2502** [Dulce-Work-Schedule/2018.1-Dulce_App#326]
Conversa sobre como está sendo avaliada a forma que estamos avaliando a probabilidade de acontecimentos.
- https://pt.linkedin.com/pulse/gerenciamento-de-riscos-em-projetos-%C3%A1geis-parte-2-e

**Comment by alvesisaque** [comment]
Como conversado com a professora ontem, está errado o momento em que pontuamos a probabilidade desse risco acontecer, essa tarefa será alterada para o rito do planejamento. 
Aproveitamos a conversa para sanar duvidas sobre o planejamento das próximas semanas.
