### ISSUE TITLE
Estudar bibliotecas do react native

### ISSUE THREAD

**Issue by egewarth** [Dulce-Work-Schedule/2018.1-Dulce_App#327]
Nessa issue deve ser feito:
- Estudo das bibliotecas do react-native relacionadas ás telas de editar horário e troca de plantão

**Comment by vitorl-s** [comment]
@gdeusdara @EzequielDeOliveira  vocês ja escolheram a biblioteca de vcs?

**Comment by egewarth** [comment]
@gdeusdara, @EzequielDeOliveira , @vitorl-s , @gabibguedes, @fepas , @BeatrizHanae . Como está o andamento dessa Issue? Assim que definirem a ferramenta marca a issue como concluida. Faz bem pro BurnDown

**Comment by egewarth** [comment]
Comentem aqui se já escolheram, assim todos conseguem ver. Comentem também as decisões tomadas, qual biblioteca foi escolhida pra resolver tal issue.

**Comment by vitorl-s** [comment]
@egewarth já definimos a biblioteca que iremos utilizar, postarei o link dela agora. Temos que ver se o @gdeusdara e @EzequielDeOliveira ja escolheram antes de fechar

**Comment by vitorl-s** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker

**Comment by egewarth** [comment]
@vitorl-s Sim, o ideal é que todos postem ou ao menos comentem a situação, se não encontraram falem tbm.

**Comment by vitorl-s** [comment]
@egewarth Essa que escolhemos parece funcionar bem, faremos o teste ainda

**Comment by gdeusdara** [comment]
Na real que pra troca de plantão estamos usando a Modal do react-native msm além da biblioteca que já foi utilizada pra visualizar horário, só estamos finalizando aqui e vamos mandar pr hj

**Comment by vitorl-s** [comment]
@gdeusdara entao pode fechar a issue, agt ja escolheu as bibliotecas
