### ISSUE TITLE
Estudar modelagem de dados

### ISSUE THREAD

**Issue by BeatrizHanae** [Dulce-Work-Schedule/2018.1-Dulce_App#329]
Conteúdo da issue:
- Nessa issue é para estudar a modelagem de dados relacionado ao MONGO DB

Nessa issue será realizado:
- Deverá ter estudo relacionado ao Banco de dados.

**Comment by egewarth** [comment]
Foi estudado:
- https://docs.mongodb.com/manual/core/data-modeling-introduction/
- https://docs.mongodb.com/manual/core/data-model-design/
- https://pt.slideshare.net/jhonathanmarolo/introduo-ao-nosql-e-modelagem-de-dados-com-mongodb
