### ISSUE TITLE
Tela de editar horário do plantonista.

### ISSUE THREAD

**Issue by BeatrizHanae** [Dulce-Work-Schedule/2018.1-Dulce_App#330]
Conteúdo da issue:
- Nessa issue deverá ser feito a tela que solicita edição do horário.

Nessa issue será realizado:
- Visual

Critérios de aceitação:
- Visual;
- Validação.

**Comment by alvesisaque** [comment]
Isso é uma história de usuário?

**Comment by fepas** [comment]
@egewarth, essa é a tela de edição, ou de troca entre usuários?

**Comment by fepas** [comment]
@egewarth

**Comment by egewarth** [comment]
@fepas opa

**Comment by egewarth** [comment]
troca de usuários está definida em outra issue. Essa, como descrito, é apenas de edição de horário.

**Comment by fepas** [comment]
Obrigado!

**Comment by egewarth** [comment]
@fepas desculpa, não vi o comentário mais cedo

**Comment by fepas** [comment]
relaxa meu consagrado <3

**Comment by alvesisaque** [comment]
@fepas @vitorl-s finalizem o quanto antes essa atividade, conseguem finalizar hoje ainda?

**Comment by fepas** [comment]
@alvesisaque Não sei se a gente vai conseguir parear hoje, e não é algo tão trivial, então é provável que não.

**Comment by alvesisaque** [comment]
@fepas é melhor transferir essa atividade a outra dupla? Por não ser algo trivial e um débito técnico, precisa ser iniciada logo

**Comment by fepas** [comment]
@alvesisaque Creio que sim, acho que seria bom, pra não misturar as duplas dessa semana. Mas posso participar pra ajudar no pareamento.

**Comment by alvesisaque** [comment]
@fepas Não concordo com essa decisão. Mas como não quero atrapalhar o andamento do time, essa issue será direcionada para a dupla @Jimmy2201 e @EzequielDeOliveira

**Comment by EzequielDeOliveira** [comment]
@alvesisaque Ok mas hj e não mecho
