### ISSUE TITLE
Tela de solicitar troca de plantão

### ISSUE THREAD

**Issue by BeatrizHanae** [Dulce-Work-Schedule/2018.1-Dulce_App#331]
Conteúdo da issue:
- Nessa issue deverá ser feito a tela que solicita a troca de plantão com outro plantonista.

Nessa issue será realizado:
- Visual

Critérios de aceitação:
- Visual;
- Validação.

**Comment by egewarth** [comment]
Nessa issue deve ser feita a tela de troca de escalas seguindo o protótipo.
O plantonista ao ver a escala do setor pode selecionar um horário preenchido (seu ou de outro plantonista) e solicitar a troca de plantão, caso clique no seu horário ele deve selecionar horário de outra pessoa pra trocar, caso clique no horário de outra pessoa deve selecionar um horário seu

**Comment by egewarth** [comment]
Isso a partir da issue feita pelo Ezequiel e pela Gabi

**Comment by gdeusdara** [comment]
ok
