### ISSUE TITLE
Fazer a modelagem de dados

### ISSUE THREAD

**Issue by BeatrizHanae** [Dulce-Work-Schedule/2018.1-Dulce_App#332]
Nessa issue deverá ser feito:
### A modelagem de dados:
- User (Cadastro Social e Cadastro normal)
- Profile (Perfil de um hospital)
- Schedule (Escala)
- Schedule (Horario)
- Solicitação de troca (?)
- Sector 
- Hospital

**Comment by alvesisaque** [comment]
Devido ao replanejamento durante a sprint 10, onde a prioridade maior é o deploy contínuo, as atividades dessa issue estão suspensas até ser planejada novamente.

**Comment by egewarth** [comment]
@EzequielDeOliveira e @vitorl-s e @eliseuegewarth , vamos fazer essa Issue segunda feira? Acho que seria uma boa pra gente adiantar a semana.

**Comment by EzequielDeOliveira** [comment]
@eliseuegewarth Fico na fga até às 12 na segunda

**Comment by EzequielDeOliveira** [comment]
@EzequielDeOliveira Hangouts a qualquer HR
