### ISSUE TITLE
Aplicar redux no logout

### ISSUE THREAD

**Issue by gabibguedes** [Dulce-Work-Schedule/2018.1-Dulce_App#346]
Nessa issue será realizado:
- [x] Consertar redux para logout
- [ ] Impedir que o usuário volte para a parte logada após logout pelo botão de voltar

**Comment by EzequielDeOliveira** [comment]
@gabibguedes Redux pra logout já foi

**Comment by gabibguedes** [comment]
@EzequielDeOliveira Não tá funcionando parece
