### ISSUE TITLE
Garantir qualidade de código

### ISSUE THREAD

**Issue by BeatrizHanae** [Dulce-Work-Schedule/2018.1-Dulce_App#351]
Conteúdo da issue
É um épico para garantir a qualidade e cobertura do código.

- Cobertura de teste em locais que estão faltando;
- Manuteabilidade do código.

Critérios de aceitação:
- [x] Coverage 75%;
- [x] Coverage 85%;
- [x] Manuteabildade: A.

**Comment by gabibguedes** [comment]
Foi feito os 75% de testes, entretanto, ao juntar com a master a porcentagem diminuiu devido a falta de testes em uma nova funcionalidade desenvolvida nesta sprint
