### ISSUE TITLE
Reunião para trocar figurinhas PT 2

### ISSUE THREAD

**Issue by alvesisaque** [Dulce-Work-Schedule/2018.1-Dulce_App#371]
- Conversar sobre o planejamento da Release 2
- Ajustar o planejamento para entregar a tempo da campus party
- Conversar sobre o nosso produto

**Comment by eliseuegewarth** [comment]
@alvesisaque Da release 2 não?

**Comment by alvesisaque** [comment]
@alvesisaque @GabyUnB @joaoegewarth @eliseuegewarth. Podemos marcar essa reunião para amanha à tarde?

**Comment by alvesisaque** [comment]
@eliseuegewarth Corrigido!

**Comment by egewarth** [comment]
@alvesisaque Que hrs?

**Comment by gag2502** [comment]
@alvesisaque Yes
