### ISSUE TITLE
Estudar biblioteca de upload file

### ISSUE THREAD

**Issue by vitorl-s** [Dulce-Work-Schedule/2018.1-Dulce_App#379]
Nessa issue deve ser feito:
- Estudar biblioteca de upload file para ser usada na #382 
- Verificar se condiz com o design do app

**Comment by BeatrizHanae** [comment]
Gente, é so a parte front-end dessa parte né? De ter uma opção pra abrir as fotos ou a câmera para dar upload. Certo?

**Comment by BeatrizHanae** [comment]
Pelo que eu vi na issue 383, agora faz sentido. Esquece.

**Comment by egewarth** [comment]
@BeatrizHanae Isso, só front end essa semana

**Comment by gdeusdara** [comment]
https://www.npmjs.com/package/react-native-photo-upload

**Comment by gdeusdara** [comment]
https://github.com/g6ling/React-Native-Tips/tree/master/How_to_upload_photo%2Cfile_in%20react-native

**Comment by gdeusdara** [comment]
https://snowball.digital/Blog/Uploading-Images-in-React-Native

**Comment by egewarth** [comment]
@gdeusdara Não esqueçam que não é só foto, é arquivo jpg, png ou pdf

**Comment by gdeusdara** [comment]
@egewarth hmmm verdade

**Comment by gdeusdara** [comment]
@egewarth ok

**Comment by BeatrizHanae** [comment]
Indicação do Sr. Amoedo:
https://github.com/react-community/react-native-image-picker/blob/develop/README.md

**Comment by gdeusdara** [comment]
@BeatrizHanae  vamos usar essa do Amoedo, muito boa mesmo
