### ISSUE TITLE
Estudar como estilizar SideMenu

### ISSUE THREAD

**Issue by gabibguedes** [Dulce-Work-Schedule/2018.1-Dulce_App#385]
Estudar como aplicar estilo no side menu

**Comment by fepas** [comment]
https://codeburst.io/custom-drawer-using-react-navigation-80abbab489f7

Encontramos esse guia que já tinha sido indicado a mim pelo @EzequielDeOliveira, creio que será a melhor opção. 
Git da aplicação:
https://github.com/kakulgupta/CustomDrawer
