### ISSUE TITLE
Cadastro User

### ISSUE THREAD

**Issue by EzequielDeOliveira** [Dulce-Work-Schedule/2018.1-Dulce_App#389]
nessa issue deve ser feito:
- Refatorar tela cad. User

**Comment by eliseuegewarth** [comment]
Detalhar o que deverá ser feito nessa issue. A funcionalidade entregue nesta tela não será modificada? Caso contrário, não utilize "refatorar".

**Comment by eliseuegewarth** [comment]
@vitorl-s @fepas @EzequielDeOliveira
