### ISSUE TITLE
Modificar tela de Login para permitir login social

### ISSUE THREAD

**Issue by EzequielDeOliveira** [Dulce-Work-Schedule/2018.1-Dulce_App#390]
nessa issue deve ser feito:
- Refatorar tela de Login para possibilitar login social

**Comment by egewarth** [comment]
https://github.com/react-native-community/react-native-google-signin

**Comment by egewarth** [comment]
Veja como fazer o botão [aqui](https://github.com/react-native-community/react-native-google-signin#1-googlesigninbutton)

**Comment by egewarth** [comment]
https://www.npmjs.com/package/react-google-button
