### ISSUE TITLE
Informativo

### ISSUE THREAD

**Issue by egewarth** [Dulce-Work-Schedule/2018.1-Dulce_App#444]
@RochaCarla , caso queira ver a frequencia de entregas do nosso projeto, veja os commits da [Dulce](https://github.com/Dulce-Work-Schedule/2018.1-Dulce_App/commits?author=dulce-bot).
Cada commit (da Dulce) é uma nova versão Beta do nosso projeto. Versões oficiais são lançadas aos sabados junto com a Tag da sprint.

**Comment by RochaCarla** [comment]
blz
